/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author dhiys
 */
public class CardRollingScreen extends javax.swing.JFrame {

    /**
     * Creates new form CardRollingScreen
     */
    public CardRollingScreen() {

        initComponents();
        boolean hasDupe = true;
        while (hasDupe) {
            BACKEND.DiceAndHandManager.addSpecialCards(6, 1, 3);
            if (!BACKEND.DiceAndHandManager.cardHandHasDupe()) {
                nameCardLabel.setText(BACKEND.DiceAndHandManager.returnCardInHand(0).getName());
                descripTA.setText(BACKEND.DiceAndHandManager.returnCardInHand(0).getDescription());

                nameCardLabel1.setText(BACKEND.DiceAndHandManager.returnCardInHand(1).getName());
                descripTA1.setText(BACKEND.DiceAndHandManager.returnCardInHand(1).getDescription());

                nameCardLabel2.setText(BACKEND.DiceAndHandManager.returnCardInHand(2).getName());
                descripTA2.setText(BACKEND.DiceAndHandManager.returnCardInHand(2).getDescription());

//                nameCardLabel3.setText(BACKEND.DiceAndHandManager.returnCardInHand(3).getName());
//                descripTA3.setText(BACKEND.DiceAndHandManager.returnCardInHand(3).getDescription());
//                typeLab3.setText(BACKEND.DiceAndHandManager.returnCardInHand(3).getTypeAction());
//                costLab3.setText(""+BACKEND.DiceAndHandManager.returnCardInHand(3).getCost());
//                nameCardLabel4.setText(BACKEND.DiceAndHandManager.returnCardInHand(4).getName());
//                descripTA4.setText(BACKEND.DiceAndHandManager.returnCardInHand(4).getDescription());
//                typeLab4.setText(BACKEND.DiceAndHandManager.returnCardInHand(4).getTypeAction());
//                costLab4.setText(""+BACKEND.DiceAndHandManager.returnCardInHand(4).getCost());
                hasDupe = false;
                break;
            } else {
                BACKEND.DiceAndHandManager.clearHand();
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        goToBattleScreen = new javax.swing.JButton();
        viewSpecCardPanel2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        nameCardLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        descripTA2 = new javax.swing.JTextArea();
        viewSpecCardPanel1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        nameCardLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripTA1 = new javax.swing.JTextArea();
        viewSpecCardPanel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        nameCardLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 19, 18));
        jPanel1.setPreferredSize(new java.awt.Dimension(1490, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(109, 161, 213));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(215, 148, 203));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/questionBook.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 150, 150));

        jLabel9.setBackground(new java.awt.Color(109, 161, 213));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(215, 148, 203));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/questionBook.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 150, 150));

        jLabel2.setBackground(new java.awt.Color(109, 161, 213));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(215, 148, 203));
        jLabel2.setText("Special Cards in Hand ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        goToBattleScreen.setBackground(new java.awt.Color(65, 49, 65));
        goToBattleScreen.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        goToBattleScreen.setForeground(new java.awt.Color(228, 217, 226));
        goToBattleScreen.setText("Next");
        goToBattleScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToBattleScreenActionPerformed(evt);
            }
        });
        jPanel1.add(goToBattleScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 690, 270, 80));

        viewSpecCardPanel2.setBackground(new java.awt.Color(26, 23, 25));
        viewSpecCardPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(228, 217, 226));
        jLabel29.setText("Description:");
        viewSpecCardPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, 43));

        nameCardLabel2.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        nameCardLabel2.setForeground(new java.awt.Color(228, 217, 226));
        nameCardLabel2.setText("Name:");
        viewSpecCardPanel2.add(nameCardLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 250, 43));

        descripTA2.setBackground(new java.awt.Color(26, 23, 25));
        descripTA2.setColumns(20);
        descripTA2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        descripTA2.setForeground(new java.awt.Color(228, 217, 226));
        descripTA2.setRows(5);
        jScrollPane3.setViewportView(descripTA2);

        viewSpecCardPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, 330, 100));

        jPanel1.add(viewSpecCardPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 180, 350, 470));

        viewSpecCardPanel1.setBackground(new java.awt.Color(26, 23, 25));
        viewSpecCardPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(228, 217, 226));
        jLabel26.setText("Description:");
        viewSpecCardPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, 43));

        nameCardLabel1.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        nameCardLabel1.setForeground(new java.awt.Color(228, 217, 226));
        nameCardLabel1.setText("Name:");
        viewSpecCardPanel1.add(nameCardLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 250, 43));

        descripTA1.setBackground(new java.awt.Color(26, 23, 25));
        descripTA1.setColumns(20);
        descripTA1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        descripTA1.setForeground(new java.awt.Color(228, 217, 226));
        descripTA1.setRows(5);
        jScrollPane2.setViewportView(descripTA1);

        viewSpecCardPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, 320, 100));

        jPanel1.add(viewSpecCardPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 340, 470));

        viewSpecCardPanel.setBackground(new java.awt.Color(26, 23, 25));
        viewSpecCardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(228, 217, 226));
        jLabel24.setText("Description:");
        viewSpecCardPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, 43));

        nameCardLabel.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        nameCardLabel.setForeground(new java.awt.Color(228, 217, 226));
        nameCardLabel.setText("Name:");
        viewSpecCardPanel.add(nameCardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 250, 43));

        descripTA.setBackground(new java.awt.Color(26, 23, 25));
        descripTA.setColumns(20);
        descripTA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        descripTA.setForeground(new java.awt.Color(228, 217, 226));
        descripTA.setRows(5);
        jScrollPane1.setViewportView(descripTA);

        viewSpecCardPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, 340, 100));

        jPanel1.add(viewSpecCardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 360, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goToBattleScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToBattleScreenActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        BattleScreen bs = new BattleScreen();
        bs.setVisible(true);
    }//GEN-LAST:event_goToBattleScreenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardRollingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardRollingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardRollingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardRollingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardRollingScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descripTA;
    private javax.swing.JTextArea descripTA1;
    private javax.swing.JTextArea descripTA2;
    private javax.swing.JButton goToBattleScreen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nameCardLabel;
    private javax.swing.JLabel nameCardLabel1;
    private javax.swing.JLabel nameCardLabel2;
    private javax.swing.JPanel viewSpecCardPanel;
    private javax.swing.JPanel viewSpecCardPanel1;
    private javax.swing.JPanel viewSpecCardPanel2;
    // End of variables declaration//GEN-END:variables
}
