/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.Color;

/**
 *
 * @author dhiys
 */
public class DeckCharCreatorScreen extends javax.swing.JFrame {

    /**
     * Creates new form DeskCreatorScreen
     */
    public DeckCharCreatorScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        charDeskMakerButGrp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        baalTogBut = new javax.swing.JToggleButton();
        childeTogBut = new javax.swing.JToggleButton();
        dilucTogBut = new javax.swing.JToggleButton();
        ganyuTogBut = new javax.swing.JToggleButton();
        huTaoTogBut = new javax.swing.JToggleButton();
        kaeyaTogBut = new javax.swing.JToggleButton();
        goToAddSpecCardBut = new javax.swing.JButton();
        monaTogBut = new javax.swing.JToggleButton();
        scaraTogBut = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        clearDeckBut = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        returnToMMBut = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        deckInstrucLab = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        deckInstrucLab1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(20, 19, 18));
        jPanel1.setForeground(new java.awt.Color(65, 49, 65));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(228, 217, 226));
        jLabel2.setText("Hu Tao:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(228, 217, 226));
        jLabel9.setText("Diluc:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(228, 217, 226));
        jLabel4.setText("Childe:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 640, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(228, 217, 226));
        jLabel5.setText("Mona:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(228, 217, 226));
        jLabel6.setText("Scaramouche:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 640, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(228, 217, 226));
        jLabel7.setText("Baal:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 640, -1, -1));

        baalTogBut.setBackground(new java.awt.Color(65, 49, 65));
        charDeskMakerButGrp.add(baalTogBut);
        baalTogBut.setForeground(new java.awt.Color(65, 49, 65));
        baalTogBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BaalMeow.jpg"))); // NOI18N
        baalTogBut.setMaximumSize(new java.awt.Dimension(50, 50));
        baalTogBut.setMinimumSize(new java.awt.Dimension(0, 0));
        baalTogBut.setPreferredSize(new java.awt.Dimension(50, 50));
        baalTogBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baalTogButActionPerformed(evt);
            }
        });
        jPanel1.add(baalTogBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, 157, 157));

        childeTogBut.setBackground(new java.awt.Color(65, 49, 65));
        charDeskMakerButGrp.add(childeTogBut);
        childeTogBut.setForeground(new java.awt.Color(65, 49, 65));
        childeTogBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ChildeMeow.jpg"))); // NOI18N
        childeTogBut.setPreferredSize(new java.awt.Dimension(157, 157));
        childeTogBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childeTogButActionPerformed(evt);
            }
        });
        jPanel1.add(childeTogBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        dilucTogBut.setBackground(new java.awt.Color(65, 49, 65));
        charDeskMakerButGrp.add(dilucTogBut);
        dilucTogBut.setForeground(new java.awt.Color(65, 49, 65));
        dilucTogBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DilucMeow.jpg"))); // NOI18N
        dilucTogBut.setMaximumSize(new java.awt.Dimension(145, 145));
        dilucTogBut.setMinimumSize(new java.awt.Dimension(0, 0));
        dilucTogBut.setPreferredSize(new java.awt.Dimension(145, 145));
        dilucTogBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dilucTogButActionPerformed(evt);
            }
        });
        jPanel1.add(dilucTogBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 157, 157));

        ganyuTogBut.setBackground(new java.awt.Color(65, 49, 65));
        charDeskMakerButGrp.add(ganyuTogBut);
        ganyuTogBut.setForeground(new java.awt.Color(65, 49, 65));
        ganyuTogBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GanyuMeow.jpg"))); // NOI18N
        ganyuTogBut.setMaximumSize(new java.awt.Dimension(145, 145));
        ganyuTogBut.setMinimumSize(new java.awt.Dimension(0, 0));
        ganyuTogBut.setPreferredSize(new java.awt.Dimension(145, 145));
        ganyuTogBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ganyuTogButActionPerformed(evt);
            }
        });
        jPanel1.add(ganyuTogBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, 157, 157));

        huTaoTogBut.setBackground(new java.awt.Color(65, 49, 65));
        charDeskMakerButGrp.add(huTaoTogBut);
        huTaoTogBut.setForeground(new java.awt.Color(65, 49, 65));
        huTaoTogBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HuTaoMeow.jpg"))); // NOI18N
        huTaoTogBut.setMaximumSize(new java.awt.Dimension(145, 145));
        huTaoTogBut.setMinimumSize(new java.awt.Dimension(0, 0));
        huTaoTogBut.setPreferredSize(new java.awt.Dimension(145, 145));
        huTaoTogBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huTaoTogButActionPerformed(evt);
            }
        });
        jPanel1.add(huTaoTogBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 157, 157));

        kaeyaTogBut.setBackground(new java.awt.Color(65, 49, 65));
        charDeskMakerButGrp.add(kaeyaTogBut);
        kaeyaTogBut.setForeground(new java.awt.Color(65, 49, 65));
        kaeyaTogBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/KaeyaMeow.jpg"))); // NOI18N
        kaeyaTogBut.setMaximumSize(new java.awt.Dimension(145, 145));
        kaeyaTogBut.setMinimumSize(new java.awt.Dimension(0, 0));
        kaeyaTogBut.setPreferredSize(new java.awt.Dimension(145, 145));
        kaeyaTogBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaeyaTogButActionPerformed(evt);
            }
        });
        jPanel1.add(kaeyaTogBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 200, 157, 157));

        goToAddSpecCardBut.setBackground(new java.awt.Color(65, 49, 65));
        goToAddSpecCardBut.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        goToAddSpecCardBut.setForeground(new java.awt.Color(232, 214, 232));
        goToAddSpecCardBut.setText("Go To Add Special Cards Next");
        goToAddSpecCardBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToAddSpecCardButActionPerformed(evt);
            }
        });
        jPanel1.add(goToAddSpecCardBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 710, 300, 50));

        monaTogBut.setBackground(new java.awt.Color(65, 49, 65));
        charDeskMakerButGrp.add(monaTogBut);
        monaTogBut.setForeground(new java.awt.Color(65, 49, 65));
        monaTogBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MonaMeow.jpg"))); // NOI18N
        monaTogBut.setMaximumSize(new java.awt.Dimension(145, 145));
        monaTogBut.setMinimumSize(new java.awt.Dimension(0, 0));
        monaTogBut.setPreferredSize(new java.awt.Dimension(145, 145));
        monaTogBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monaTogButActionPerformed(evt);
            }
        });
        jPanel1.add(monaTogBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 157, 157));

        scaraTogBut.setBackground(new java.awt.Color(65, 49, 65));
        charDeskMakerButGrp.add(scaraTogBut);
        scaraTogBut.setForeground(new java.awt.Color(65, 49, 65));
        scaraTogBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ScaraMeow.jpg"))); // NOI18N
        scaraTogBut.setMaximumSize(new java.awt.Dimension(145, 145));
        scaraTogBut.setMinimumSize(new java.awt.Dimension(0, 0));
        scaraTogBut.setPreferredSize(new java.awt.Dimension(145, 145));
        scaraTogBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scaraTogButActionPerformed(evt);
            }
        });
        jPanel1.add(scaraTogBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 470, 157, 157));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(228, 217, 226));
        jLabel3.setText("Ganyu:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(228, 217, 226));
        jLabel8.setText("Kaeya:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 370, -1, -1));

        clearDeckBut.setBackground(new java.awt.Color(65, 49, 65));
        clearDeckBut.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        clearDeckBut.setForeground(new java.awt.Color(232, 214, 232));
        clearDeckBut.setText("Clear Deck");
        clearDeckBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearDeckButActionPerformed(evt);
            }
        });
        jPanel1.add(clearDeckBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 710, 140, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("RETURN TO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 100));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("MAIN MENU");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 100));

        returnToMMBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/90x90button.png"))); // NOI18N
        returnToMMBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToMMButActionPerformed(evt);
            }
        });
        jPanel1.add(returnToMMBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 100));

        jLabel12.setBackground(new java.awt.Color(109, 161, 213));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(215, 148, 203));
        jLabel12.setText("Character Deck Creator");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        deckInstrucLab.setBackground(new java.awt.Color(109, 161, 213));
        deckInstrucLab.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        deckInstrucLab.setForeground(new java.awt.Color(228, 217, 226));
        deckInstrucLab.setText("*the numbers are physical attack damage, skill attack damage, burst attack damage");
        deckInstrucLab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(deckInstrucLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(228, 217, 226));
        jLabel13.setText("2, 3, 6");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(228, 217, 226));
        jLabel14.setText("2, 3, 6");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(228, 217, 226));
        jLabel15.setText("2, 3, 4");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 370, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(228, 217, 226));
        jLabel16.setText("2, 3, 4");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 370, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(228, 217, 226));
        jLabel17.setText("2, 3, 4");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 640, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(228, 217, 226));
        jLabel18.setText("2, 3, 5");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 640, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(228, 217, 226));
        jLabel19.setText("1, 2, 3");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 640, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(228, 217, 226));
        jLabel20.setText("3, 4, 6");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 640, -1, -1));

        deckInstrucLab1.setBackground(new java.awt.Color(109, 161, 213));
        deckInstrucLab1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deckInstrucLab1.setForeground(new java.awt.Color(228, 217, 226));
        deckInstrucLab1.setText("Choose 3 characters to be in your deck.");
        deckInstrucLab1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(deckInstrucLab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        jLabel21.setBackground(new java.awt.Color(109, 161, 213));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(215, 148, 203));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/catBox.jpg"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 150, 150));

        jLabel23.setBackground(new java.awt.Color(109, 161, 213));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(215, 148, 203));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/catStretch (1).jpg"))); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 210, 150, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1490, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baalTogButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baalTogButActionPerformed
        // TODO add your handling code here:
        BACKEND.DeckManager.selectCharsFromInfoDB("Baal");
        
    }//GEN-LAST:event_baalTogButActionPerformed

    private void childeTogButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childeTogButActionPerformed
        // TODO add your handling code here:
        BACKEND.DeckManager.selectCharsFromInfoDB("Childe");
        
    }//GEN-LAST:event_childeTogButActionPerformed

    private void kaeyaTogButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaeyaTogButActionPerformed
        // TODO add your handling code here:
        BACKEND.DeckManager.selectCharsFromInfoDB("Kaeya");

    }//GEN-LAST:event_kaeyaTogButActionPerformed

    private void goToAddSpecCardButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToAddSpecCardButActionPerformed
        // TODO add your handling code here:
       // BACKEND.DeckManager.printChars();
        if (BACKEND.DeckManager.hasDupeCharacters()) {
            deckInstrucLab.setText("Duplicate characters found. Clear deck and retry.");
            deckInstrucLab.setForeground(Color.RED);
        } else if (BACKEND.DeckManager.isCompleteCharacterDeck()) {
            this.setVisible(false);
            DeckCardCreatorScreen cardCreateScr = new DeckCardCreatorScreen();
            cardCreateScr.setVisible(true);
        }else{
            deckInstrucLab.setText("Need 3 characters MAX.");
            deckInstrucLab.setForeground(Color.RED);
        }

    }//GEN-LAST:event_goToAddSpecCardButActionPerformed

    private void clearDeckButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearDeckButActionPerformed
        // TODO add your handling code here:
        BACKEND.DeckManager.clearCharacterDeck();
        deckInstrucLab.setText("Deck cleared. Rechoose another 3.");
        deckInstrucLab.setForeground(Color.RED);
       // BACKEND.DeckManager.removeCharsFromActiveDB();
    }//GEN-LAST:event_clearDeckButActionPerformed

    private void dilucTogButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dilucTogButActionPerformed
        // TODO add your handling code here:
        BACKEND.DeckManager.selectCharsFromInfoDB("Diluc");
        //

    }//GEN-LAST:event_dilucTogButActionPerformed

    private void huTaoTogButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huTaoTogButActionPerformed
        // TODO add your handling code here:
        BACKEND.DeckManager.selectCharsFromInfoDB("Hu Tao");

    }//GEN-LAST:event_huTaoTogButActionPerformed

    private void ganyuTogButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ganyuTogButActionPerformed
        // TODO add your handling code here:
        BACKEND.DeckManager.selectCharsFromInfoDB("Ganyu");
        
    }//GEN-LAST:event_ganyuTogButActionPerformed

    private void monaTogButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monaTogButActionPerformed
        // TODO add your handling code here:
        BACKEND.DeckManager.selectCharsFromInfoDB("Mona");
        
    }//GEN-LAST:event_monaTogButActionPerformed

    private void scaraTogButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scaraTogButActionPerformed
        // TODO add your handling code here:
        BACKEND.DeckManager.selectCharsFromInfoDB("Scaramouche");
        
    }//GEN-LAST:event_scaraTogButActionPerformed

    private void returnToMMButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToMMButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainMenuScreen mms = new MainMenuScreen();
        mms.setVisible(true);
        BACKEND.DeckManager.clearCharacterDeck();
    }//GEN-LAST:event_returnToMMButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeckCharCreatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeckCharCreatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeckCharCreatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeckCharCreatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeckCharCreatorScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton baalTogBut;
    private javax.swing.ButtonGroup charDeskMakerButGrp;
    private javax.swing.JToggleButton childeTogBut;
    private javax.swing.JButton clearDeckBut;
    private javax.swing.JLabel deckInstrucLab;
    private javax.swing.JLabel deckInstrucLab1;
    private javax.swing.JToggleButton dilucTogBut;
    private javax.swing.JToggleButton ganyuTogBut;
    private javax.swing.JButton goToAddSpecCardBut;
    private javax.swing.JToggleButton huTaoTogBut;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton kaeyaTogBut;
    private javax.swing.JToggleButton monaTogBut;
    private javax.swing.JButton returnToMMBut;
    private javax.swing.JToggleButton scaraTogBut;
    // End of variables declaration//GEN-END:variables
}
