/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.Color;

/**
 *
 * @author dhiys
 */
public class DeckCardCreatorScreen extends javax.swing.JFrame {

    /**
     * Creates new form DeckCardCreatorScreen
     */
    public DeckCardCreatorScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardDeskMakerButGrp = new javax.swing.ButtonGroup();
        cardCreatorPanel = new javax.swing.JPanel();
        finishDeckBut = new javax.swing.JButton();
        clearDeckBut = new javax.swing.JButton();
        IncPyroDmgBut = new javax.swing.JToggleButton();
        IncCryoDmgBut = new javax.swing.JToggleButton();
        IncElectroDmgBut = new javax.swing.JToggleButton();
        IncHydroDmgBut = new javax.swing.JToggleButton();
        OneLessDiceBut = new javax.swing.JToggleButton();
        HealTwoHPBut = new javax.swing.JToggleButton();
        healOneHP = new javax.swing.JToggleButton();
        IncPolearmDmgBut = new javax.swing.JToggleButton();
        IncBowDmgBut = new javax.swing.JToggleButton();
        Deal3DmgBut = new javax.swing.JToggleButton();
        IncClaymoreDmgBut = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        returnToCharDeskBut = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        deckInstrucLab = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardCreatorPanel.setBackground(new java.awt.Color(20, 19, 18));
        cardCreatorPanel.setPreferredSize(new java.awt.Dimension(1490, 800));
        cardCreatorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        finishDeckBut.setBackground(new java.awt.Color(65, 49, 65));
        finishDeckBut.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        finishDeckBut.setForeground(new java.awt.Color(228, 217, 226));
        finishDeckBut.setText("Finish Creating Full Deck");
        finishDeckBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishDeckButActionPerformed(evt);
            }
        });
        cardCreatorPanel.add(finishDeckBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 530, 290, 80));

        clearDeckBut.setBackground(new java.awt.Color(65, 49, 65));
        clearDeckBut.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        clearDeckBut.setForeground(new java.awt.Color(228, 217, 226));
        clearDeckBut.setText("Clear Deck");
        clearDeckBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearDeckButActionPerformed(evt);
            }
        });
        cardCreatorPanel.add(clearDeckBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 630, 290, 80));

        IncPyroDmgBut.setBackground(new java.awt.Color(65, 49, 65));
        cardDeskMakerButGrp.add(IncPyroDmgBut);
        IncPyroDmgBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IncPyroDmgBut.setForeground(new java.awt.Color(228, 217, 226));
        IncPyroDmgBut.setText("Increase Pyro Damage");
        IncPyroDmgBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncPyroDmgButActionPerformed(evt);
            }
        });
        cardCreatorPanel.add(IncPyroDmgBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 220, 80));

        IncCryoDmgBut.setBackground(new java.awt.Color(65, 49, 65));
        cardDeskMakerButGrp.add(IncCryoDmgBut);
        IncCryoDmgBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IncCryoDmgBut.setForeground(new java.awt.Color(228, 217, 226));
        IncCryoDmgBut.setText("Increase Cryo Damage");
        IncCryoDmgBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncCryoDmgButActionPerformed(evt);
            }
        });
        cardCreatorPanel.add(IncCryoDmgBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 220, 80));

        IncElectroDmgBut.setBackground(new java.awt.Color(65, 49, 65));
        cardDeskMakerButGrp.add(IncElectroDmgBut);
        IncElectroDmgBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IncElectroDmgBut.setForeground(new java.awt.Color(228, 217, 226));
        IncElectroDmgBut.setText("Increase Electro Damage");
        IncElectroDmgBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncElectroDmgButActionPerformed(evt);
            }
        });
        cardCreatorPanel.add(IncElectroDmgBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 220, 80));

        IncHydroDmgBut.setBackground(new java.awt.Color(65, 49, 65));
        cardDeskMakerButGrp.add(IncHydroDmgBut);
        IncHydroDmgBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IncHydroDmgBut.setForeground(new java.awt.Color(228, 217, 226));
        IncHydroDmgBut.setText("Increase Hydro Damage");
        IncHydroDmgBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncHydroDmgButActionPerformed(evt);
            }
        });
        cardCreatorPanel.add(IncHydroDmgBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, 220, 80));

        OneLessDiceBut.setBackground(new java.awt.Color(65, 49, 65));
        cardDeskMakerButGrp.add(OneLessDiceBut);
        OneLessDiceBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OneLessDiceBut.setForeground(new java.awt.Color(228, 217, 226));
        OneLessDiceBut.setText("Spend 1 Less Dice for Attacks");
        OneLessDiceBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneLessDiceButActionPerformed(evt);
            }
        });
        cardCreatorPanel.add(OneLessDiceBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 230, 80));

        HealTwoHPBut.setBackground(new java.awt.Color(65, 49, 65));
        cardDeskMakerButGrp.add(HealTwoHPBut);
        HealTwoHPBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HealTwoHPBut.setForeground(new java.awt.Color(228, 217, 226));
        HealTwoHPBut.setText("Heal All Characters For 2 HP");
        HealTwoHPBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HealTwoHPButActionPerformed(evt);
            }
        });
        cardCreatorPanel.add(HealTwoHPBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 220, 80));

        healOneHP.setBackground(new java.awt.Color(65, 49, 65));
        cardDeskMakerButGrp.add(healOneHP);
        healOneHP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        healOneHP.setForeground(new java.awt.Color(228, 217, 226));
        healOneHP.setText("Heal One HP");
        healOneHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healOneHPActionPerformed(evt);
            }
        });
        cardCreatorPanel.add(healOneHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 220, 80));

        IncPolearmDmgBut.setBackground(new java.awt.Color(65, 49, 65));
        cardDeskMakerButGrp.add(IncPolearmDmgBut);
        IncPolearmDmgBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IncPolearmDmgBut.setForeground(new java.awt.Color(228, 217, 226));
        IncPolearmDmgBut.setText("Increase Polearm Damage");
        IncPolearmDmgBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncPolearmDmgButActionPerformed(evt);
            }
        });
        cardCreatorPanel.add(IncPolearmDmgBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 220, 80));

        IncBowDmgBut.setBackground(new java.awt.Color(65, 49, 65));
        cardDeskMakerButGrp.add(IncBowDmgBut);
        IncBowDmgBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IncBowDmgBut.setForeground(new java.awt.Color(228, 217, 226));
        IncBowDmgBut.setText("Increase Bow Damage");
        IncBowDmgBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncBowDmgButActionPerformed(evt);
            }
        });
        cardCreatorPanel.add(IncBowDmgBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 220, 80));

        Deal3DmgBut.setBackground(new java.awt.Color(65, 49, 65));
        cardDeskMakerButGrp.add(Deal3DmgBut);
        Deal3DmgBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Deal3DmgBut.setForeground(new java.awt.Color(228, 217, 226));
        Deal3DmgBut.setText("Deal 3 Damage For Free");
        Deal3DmgBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deal3DmgButActionPerformed(evt);
            }
        });
        cardCreatorPanel.add(Deal3DmgBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 610, 220, 80));

        IncClaymoreDmgBut.setBackground(new java.awt.Color(65, 49, 65));
        cardDeskMakerButGrp.add(IncClaymoreDmgBut);
        IncClaymoreDmgBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IncClaymoreDmgBut.setForeground(new java.awt.Color(228, 217, 226));
        IncClaymoreDmgBut.setText("Increase Claymore Damage");
        IncClaymoreDmgBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncClaymoreDmgButActionPerformed(evt);
            }
        });
        cardCreatorPanel.add(IncClaymoreDmgBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 220, 80));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("RETURN TO");
        cardCreatorPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 100));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DECK");
        cardCreatorPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 100));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CHARACTER");
        cardCreatorPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 100));

        returnToCharDeskBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/90x90button.png"))); // NOI18N
        returnToCharDeskBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToCharDeskButActionPerformed(evt);
            }
        });
        cardCreatorPanel.add(returnToCharDeskBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 100));

        jLabel12.setBackground(new java.awt.Color(109, 161, 213));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(215, 148, 203));
        jLabel12.setText("Special Cards Deck Creator");
        cardCreatorPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        deckInstrucLab.setBackground(new java.awt.Color(109, 161, 213));
        deckInstrucLab.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deckInstrucLab.setForeground(new java.awt.Color(228, 217, 226));
        deckInstrucLab.setText("Choose 6 cards to be in your deck.");
        deckInstrucLab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cardCreatorPanel.add(deckInstrucLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        jLabel32.setBackground(new java.awt.Color(109, 161, 213));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(228, 217, 226));
        jLabel32.setText("your character deck");
        jLabel32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cardCreatorPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 190, 20));

        jLabel33.setBackground(new java.awt.Color(109, 161, 213));
        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(228, 217, 226));
        jLabel33.setText("*going back will reset this and ");
        jLabel33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cardCreatorPanel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 190, 20));

        jLabel9.setBackground(new java.awt.Color(109, 161, 213));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(215, 148, 203));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cardFalling.png"))); // NOI18N
        jLabel9.setRequestFocusEnabled(false);
        cardCreatorPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 140, 370, 360));

        getContentPane().add(cardCreatorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finishDeckButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishDeckButActionPerformed
       // BACKEND.DeckManager.printCards();
        if (BACKEND.DeckManager.hasDupeCards()) {
            deckInstrucLab.setText("Duplicate cards found. Clear deck and retry.");
            deckInstrucLab.setForeground(Color.RED);
        } else if (BACKEND.DeckManager.isCompleteCardDeck()) {
            BACKEND.DeckManager.setHasADeck(true);
            BACKEND.DeckManager.addCharsToDB();
            BACKEND.DeckManager.addCardsToDB();
            this.setVisible(false);
            MainMenuScreen mms = new MainMenuScreen();
            mms.setVisible(true);
        }else{
             deckInstrucLab.setText("Either too many or too little cards added. Clear the cards and retry.");
             deckInstrucLab.setForeground(Color.RED);
        }

    }//GEN-LAST:event_finishDeckButActionPerformed

    private void clearDeckButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearDeckButActionPerformed

        BACKEND.DeckManager.clearCardDeck();
        //BACKEND.DeckManager.printCards();
        deckInstrucLab.setText("Deck cleared. Rechoose another 6.");
        deckInstrucLab.setForeground(Color.RED);
       // BACKEND.DeckManager.removeCardsFromActiveDB();
        
    }//GEN-LAST:event_clearDeckButActionPerformed

    private void HealTwoHPButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HealTwoHPButActionPerformed
        BACKEND.DeckManager.selectCardsFromInfoDB("Heal Two HP");
    }//GEN-LAST:event_HealTwoHPButActionPerformed

    private void IncPyroDmgButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncPyroDmgButActionPerformed

        BACKEND.DeckManager.selectCardsFromInfoDB("Increase Pyro Damage");
    }//GEN-LAST:event_IncPyroDmgButActionPerformed

    private void IncCryoDmgButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncCryoDmgButActionPerformed
        BACKEND.DeckManager.selectCardsFromInfoDB("Increase Cryo Damage");
    }//GEN-LAST:event_IncCryoDmgButActionPerformed

    private void IncElectroDmgButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncElectroDmgButActionPerformed
        BACKEND.DeckManager.selectCardsFromInfoDB("Increase Electro Damage");
    }//GEN-LAST:event_IncElectroDmgButActionPerformed

    private void IncHydroDmgButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncHydroDmgButActionPerformed

        BACKEND.DeckManager.selectCardsFromInfoDB("Increase Hydro Damage");
    }//GEN-LAST:event_IncHydroDmgButActionPerformed

    private void OneLessDiceButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneLessDiceButActionPerformed
        BACKEND.DeckManager.selectCardsFromInfoDB("One Less Dice");
    }//GEN-LAST:event_OneLessDiceButActionPerformed

    private void healOneHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healOneHPActionPerformed
        BACKEND.DeckManager.selectCardsFromInfoDB("Heal One HP");
    }//GEN-LAST:event_healOneHPActionPerformed

    private void IncPolearmDmgButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncPolearmDmgButActionPerformed
        BACKEND.DeckManager.selectCardsFromInfoDB("Increase Polearm Damage");
    }//GEN-LAST:event_IncPolearmDmgButActionPerformed

    private void IncClaymoreDmgButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncClaymoreDmgButActionPerformed

        BACKEND.DeckManager.selectCardsFromInfoDB("Increase Claymore Damage");
    }//GEN-LAST:event_IncClaymoreDmgButActionPerformed

    private void Deal3DmgButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deal3DmgButActionPerformed
        BACKEND.DeckManager.selectCardsFromInfoDB("Deal 3 Damage For Free");
    }//GEN-LAST:event_Deal3DmgButActionPerformed

    private void IncBowDmgButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncBowDmgButActionPerformed

        BACKEND.DeckManager.selectCardsFromInfoDB("Increase Bow Damage");
    }//GEN-LAST:event_IncBowDmgButActionPerformed

    private void returnToCharDeskButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToCharDeskButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        DeckCharCreatorScreen dccs = new DeckCharCreatorScreen();
        dccs.setVisible(true);
        BACKEND.DeckManager.clearCharacterDeck();
        BACKEND.DeckManager.clearCardDeck();
    }//GEN-LAST:event_returnToCharDeskButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeckCardCreatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeckCardCreatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeckCardCreatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeckCardCreatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeckCardCreatorScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Deal3DmgBut;
    private javax.swing.JToggleButton HealTwoHPBut;
    private javax.swing.JToggleButton IncBowDmgBut;
    private javax.swing.JToggleButton IncClaymoreDmgBut;
    private javax.swing.JToggleButton IncCryoDmgBut;
    private javax.swing.JToggleButton IncElectroDmgBut;
    private javax.swing.JToggleButton IncHydroDmgBut;
    private javax.swing.JToggleButton IncPolearmDmgBut;
    private javax.swing.JToggleButton IncPyroDmgBut;
    private javax.swing.JToggleButton OneLessDiceBut;
    private javax.swing.JPanel cardCreatorPanel;
    private javax.swing.ButtonGroup cardDeskMakerButGrp;
    private javax.swing.JButton clearDeckBut;
    private javax.swing.JLabel deckInstrucLab;
    private javax.swing.JButton finishDeckBut;
    private javax.swing.JToggleButton healOneHP;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton returnToCharDeskBut;
    // End of variables declaration//GEN-END:variables
}
