/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import BACKEND.DiceAndHandManager;
import java.awt.Color;

/**
 *
 * @author dhiys
 */
public class DiceRollingScreen extends javax.swing.JFrame {

    /**
     * Creates new form ReRollScreen
     */
    public DiceRollingScreen() {
        initComponents();
        //clearDiceBut.setVisible(false);
        BACKEND.DiceAndHandManager.setWantsReroll(false);
        BACKEND.DiceAndHandManager.addDice();
        BACKEND.DiceAndHandManager.sort();
        dice1But.setBackground(BACKEND.DiceAndHandManager.returnColour(BACKEND.DiceAndHandManager.getElement(0)));
        dice2But.setBackground(BACKEND.DiceAndHandManager.returnColour(BACKEND.DiceAndHandManager.getElement(1)));
        dice3But.setBackground(BACKEND.DiceAndHandManager.returnColour(BACKEND.DiceAndHandManager.getElement(2)));
        dice4But.setBackground(BACKEND.DiceAndHandManager.returnColour(BACKEND.DiceAndHandManager.getElement(3)));
        dice5But.setBackground(BACKEND.DiceAndHandManager.returnColour(BACKEND.DiceAndHandManager.getElement(4)));
        dice6But.setBackground(BACKEND.DiceAndHandManager.returnColour(BACKEND.DiceAndHandManager.getElement(5)));
        dice7But.setBackground(BACKEND.DiceAndHandManager.returnColour(BACKEND.DiceAndHandManager.getElement(6)));
        dice8But.setBackground(BACKEND.DiceAndHandManager.returnColour(BACKEND.DiceAndHandManager.getElement(7)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dice8But = new javax.swing.JToggleButton();
        dice1But = new javax.swing.JToggleButton();
        dice5But = new javax.swing.JToggleButton();
        dice2But = new javax.swing.JToggleButton();
        dice6But = new javax.swing.JToggleButton();
        dice3But = new javax.swing.JToggleButton();
        dice7But = new javax.swing.JToggleButton();
        dice4But = new javax.swing.JToggleButton();
        rerollDiceBut = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        clearDiceBut = new javax.swing.JButton();
        goToCardRollBut = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        returnToMainMenuBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 19, 18));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(109, 161, 213));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(215, 148, 203));
        jLabel2.setText("Roll Dice Phase");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        dice8But.setBackground(new java.awt.Color(65, 49, 65));
        dice8But.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dice8But.setForeground(new java.awt.Color(228, 217, 226));
        dice8But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dice8ButActionPerformed(evt);
            }
        });
        jPanel1.add(dice8But, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 420, 180, 180));

        dice1But.setBackground(new java.awt.Color(65, 49, 65));
        dice1But.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dice1But.setForeground(new java.awt.Color(228, 217, 226));
        dice1But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dice1ButActionPerformed(evt);
            }
        });
        jPanel1.add(dice1But, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 180, 180));

        dice5But.setBackground(new java.awt.Color(65, 49, 65));
        dice5But.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dice5But.setForeground(new java.awt.Color(228, 217, 226));
        dice5But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dice5ButActionPerformed(evt);
            }
        });
        jPanel1.add(dice5But, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 180, 180));

        dice2But.setBackground(new java.awt.Color(65, 49, 65));
        dice2But.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dice2But.setForeground(new java.awt.Color(228, 217, 226));
        dice2But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dice2ButActionPerformed(evt);
            }
        });
        jPanel1.add(dice2But, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 180, 180));

        dice6But.setBackground(new java.awt.Color(65, 49, 65));
        dice6But.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dice6But.setForeground(new java.awt.Color(228, 217, 226));
        dice6But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dice6ButActionPerformed(evt);
            }
        });
        jPanel1.add(dice6But, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 180, 180));

        dice3But.setBackground(new java.awt.Color(65, 49, 65));
        dice3But.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dice3But.setForeground(new java.awt.Color(228, 217, 226));
        dice3But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dice3ButActionPerformed(evt);
            }
        });
        jPanel1.add(dice3But, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 180, 180));

        dice7But.setBackground(new java.awt.Color(65, 49, 65));
        dice7But.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dice7But.setForeground(new java.awt.Color(228, 217, 226));
        dice7But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dice7ButActionPerformed(evt);
            }
        });
        jPanel1.add(dice7But, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 180, 180));

        dice4But.setBackground(new java.awt.Color(65, 49, 65));
        dice4But.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dice4But.setForeground(new java.awt.Color(228, 217, 226));
        dice4But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dice4ButActionPerformed(evt);
            }
        });
        jPanel1.add(dice4But, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 210, 180, 180));

        rerollDiceBut.setBackground(new java.awt.Color(65, 49, 65));
        rerollDiceBut.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        rerollDiceBut.setText("Reroll these dice");
        rerollDiceBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rerollDiceButActionPerformed(evt);
            }
        });
        jPanel1.add(rerollDiceBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 660, 290, 80));

        errorLabel.setBackground(new java.awt.Color(109, 161, 213));
        errorLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(228, 217, 226));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabel.setText("First roll.");
        errorLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 780, 50));

        clearDiceBut.setBackground(new java.awt.Color(65, 49, 65));
        clearDiceBut.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        clearDiceBut.setText("Clear dice to reroll");
        clearDiceBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearDiceButActionPerformed(evt);
            }
        });
        jPanel1.add(clearDiceBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 660, 290, 80));

        goToCardRollBut.setBackground(new java.awt.Color(65, 49, 65));
        goToCardRollBut.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        goToCardRollBut.setText("Go to special card roll next");
        goToCardRollBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToCardRollButActionPerformed(evt);
            }
        });
        jPanel1.add(goToCardRollBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 660, 290, 80));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("RETURN TO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 100));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MAIN MENU");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 100));

        returnToMainMenuBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/90x90button.png"))); // NOI18N
        returnToMainMenuBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToMainMenuButActionPerformed(evt);
            }
        });
        jPanel1.add(returnToMainMenuBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1490, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dice8ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dice8ButActionPerformed

        //then do the method
        BACKEND.DiceAndHandManager.addToRedo(7);
    }//GEN-LAST:event_dice8ButActionPerformed

    private void dice1ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dice1ButActionPerformed
        // TODO add your handling code here:

        //then do the method
        BACKEND.DiceAndHandManager.addToRedo(0);
    }//GEN-LAST:event_dice1ButActionPerformed

    private void dice5ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dice5ButActionPerformed
        // TODO add your handling code here:

        //then do the method
        BACKEND.DiceAndHandManager.addToRedo(4);
    }//GEN-LAST:event_dice5ButActionPerformed

    private void dice2ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dice2ButActionPerformed
        // TODO add your handling code here:
        //then do the method
        BACKEND.DiceAndHandManager.addToRedo(1);
    }//GEN-LAST:event_dice2ButActionPerformed

    private void dice3ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dice3ButActionPerformed
        // TODO add your handling code here:

        //then do the method
        BACKEND.DiceAndHandManager.addToRedo(2);
    }//GEN-LAST:event_dice3ButActionPerformed

    private void dice7ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dice7ButActionPerformed
        // TODO add your handling code here:

        //then do the method
        BACKEND.DiceAndHandManager.addToRedo(6);
    }//GEN-LAST:event_dice7ButActionPerformed

    private void dice4ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dice4ButActionPerformed
        // TODO add your handling code here:

        //then do the method
        BACKEND.DiceAndHandManager.addToRedo(3);
    }//GEN-LAST:event_dice4ButActionPerformed

    private void dice6ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dice6ButActionPerformed
        // TODO add your handling code here:
        BACKEND.DiceAndHandManager.addToRedo(5);
    }//GEN-LAST:event_dice6ButActionPerformed

    private void rerollDiceButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rerollDiceButActionPerformed

        BACKEND.DiceAndHandManager.rerollPositions();
        if (DiceAndHandManager.hasSelectedToReroll() && !BACKEND.DiceAndHandManager.hasDupeRerollDice()) {

            //check if theres duplicates
            BACKEND.DiceAndHandManager.sort();
            //System.out.println("going into reset method");
            dice1But.setBackground(BACKEND.DiceAndHandManager.returnColour(BACKEND.DiceAndHandManager.getElement(0)));
            dice2But.setBackground(BACKEND.DiceAndHandManager.returnColour(BACKEND.DiceAndHandManager.getElement(1)));
            dice3But.setBackground(BACKEND.DiceAndHandManager.returnColour(BACKEND.DiceAndHandManager.getElement(2)));
            dice4But.setBackground(BACKEND.DiceAndHandManager.returnColour(BACKEND.DiceAndHandManager.getElement(3)));
            dice5But.setBackground(BACKEND.DiceAndHandManager.returnColour(BACKEND.DiceAndHandManager.getElement(4)));
            dice6But.setBackground(BACKEND.DiceAndHandManager.returnColour(BACKEND.DiceAndHandManager.getElement(5)));
            dice7But.setBackground(BACKEND.DiceAndHandManager.returnColour(BACKEND.DiceAndHandManager.getElement(6)));
            dice8But.setBackground(BACKEND.DiceAndHandManager.returnColour(BACKEND.DiceAndHandManager.getElement(7)));
            BACKEND.DiceAndHandManager.setSecondRoll(true);
        }
        if (!BACKEND.DiceAndHandManager.hasSelectedToReroll()) {
            errorLabel.setForeground(Color.red);
            errorLabel.setText("No dice selected to reroll.");
        }
        if (BACKEND.DiceAndHandManager.hasDupeRerollDice()) {
            errorLabel.setForeground(Color.red);
            errorLabel.setText("Duplicate dice to reroll found. Please clear dice to reroll and retry.");

        }
        if (BACKEND.DiceAndHandManager.getSecondRoll()) {
            errorLabel.setText("Second roll done.");
            rerollDiceBut.setVisible(false);
            clearDiceBut.setVisible(false);
        }

        //need to clear the pos to reroll array again
    }//GEN-LAST:event_rerollDiceButActionPerformed

    private void clearDiceButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearDiceButActionPerformed
        // TODO add your handling code here:
        //clear the dice array and the reroll array
        dice1But.setSelected(false);
        dice2But.setSelected(false);
        dice3But.setSelected(false);
        dice4But.setSelected(false);
        dice5But.setSelected(false);
        dice6But.setSelected(false);
        dice7But.setSelected(false);
        dice8But.setSelected(false);
        errorLabel.setForeground(Color.red);
        errorLabel.setText("Dice cleared.");
        //BACKEND.DiceAndHandManager.clearDupeDice();
        BACKEND.DiceAndHandManager.clearPosToReroll();
    }//GEN-LAST:event_clearDiceButActionPerformed

    private void goToCardRollButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToCardRollButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        CardRollingScreen crs = new CardRollingScreen();
        crs.setVisible(true);
    }//GEN-LAST:event_goToCardRollButActionPerformed

    private void returnToMainMenuButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToMainMenuButActionPerformed
        // TODO add your handling code here:
        //RESET EVERYTHING IN A GAME (not decks)
        BACKEND.DiceAndHandManager.clearHand();
        BACKEND.DiceAndHandManager.clearPosToReroll();
        BACKEND.DiceAndHandManager.clearDice();
        this.setVisible(false);
        MainMenuScreen mms = new MainMenuScreen();
        mms.setVisible(true);
    }//GEN-LAST:event_returnToMainMenuButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiceRollingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiceRollingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiceRollingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiceRollingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiceRollingScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearDiceBut;
    private javax.swing.JToggleButton dice1But;
    private javax.swing.JToggleButton dice2But;
    private javax.swing.JToggleButton dice3But;
    private javax.swing.JToggleButton dice4But;
    private javax.swing.JToggleButton dice5But;
    private javax.swing.JToggleButton dice6But;
    private javax.swing.JToggleButton dice7But;
    private javax.swing.JToggleButton dice8But;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton goToCardRollBut;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton rerollDiceBut;
    private javax.swing.JButton returnToMainMenuBut;
    // End of variables declaration//GEN-END:variables
}
