/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author dhiys
 */
public class VictoryScreen extends javax.swing.JFrame {

    /**
     * Creates new form VictoryScreen
     */
    public VictoryScreen() {
        initComponents();
        //won so add 100 pts
        BACKEND.StatsManager.sumPtsInRound(100, BACKEND.LoginManager.getUser());
        if ((BACKEND.StatsManager.countTotalPts(BACKEND.LoginManager.getUser()) < 0)) {
            totalPointsLab.setText("0");
        } else {
            totalPointsLab.setText("" + BACKEND.StatsManager.countTotalPts(BACKEND.LoginManager.getUser()));
        }
        pointsInMatchLab.setText("" + BACKEND.StatsManager.getPtsInMatch());
        numMovesLab.setText("" + BACKEND.StatsManager.getNumMoves());

        congratsMessage.setText("Congratulations for conquering the evil " + BACKEND.BattleController.getActiveEnemy().getName() + ".");
        statsForLabel.setText("Stats for: " + BACKEND.LoginManager.getUser());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        returnToMMBut = new javax.swing.JButton();
        pointsInMatchLab = new javax.swing.JLabel();
        numMovesLab = new javax.swing.JLabel();
        totalPointsLab = new javax.swing.JLabel();
        congratsMessage = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        statsForLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        overlayLab = new javax.swing.JLabel();
        overlayLab1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 19, 18));
        jPanel1.setPreferredSize(new java.awt.Dimension(1490, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnToMMBut.setBackground(new java.awt.Color(65, 49, 65));
        returnToMMBut.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        returnToMMBut.setForeground(new java.awt.Color(228, 217, 226));
        returnToMMBut.setText("Return To Main menu");
        returnToMMBut.setBorder(null);
        returnToMMBut.setPreferredSize(new java.awt.Dimension(286, 84));
        returnToMMBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToMMButActionPerformed(evt);
            }
        });
        jPanel1.add(returnToMMBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 630, 290, 80));

        pointsInMatchLab.setBackground(new java.awt.Color(109, 161, 213));
        pointsInMatchLab.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        pointsInMatchLab.setForeground(new java.awt.Color(108, 40, 96));
        pointsInMatchLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(pointsInMatchLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 320, 50));

        numMovesLab.setBackground(new java.awt.Color(109, 161, 213));
        numMovesLab.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        numMovesLab.setForeground(new java.awt.Color(108, 40, 96));
        numMovesLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(numMovesLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 320, 50));

        totalPointsLab.setBackground(new java.awt.Color(109, 161, 213));
        totalPointsLab.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        totalPointsLab.setForeground(new java.awt.Color(108, 40, 96));
        totalPointsLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(totalPointsLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 320, 50));

        congratsMessage.setBackground(new java.awt.Color(109, 161, 213));
        congratsMessage.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        congratsMessage.setForeground(new java.awt.Color(108, 40, 96));
        congratsMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        congratsMessage.setText("Congratulations for conquering the evil ");
        jPanel1.add(congratsMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 1170, -1));

        jLabel6.setBackground(new java.awt.Color(109, 161, 213));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(108, 40, 96));
        jLabel6.setText("Number of moves:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        jLabel7.setBackground(new java.awt.Color(109, 161, 213));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(108, 40, 96));
        jLabel7.setText("Skill points this match: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel8.setBackground(new java.awt.Color(109, 161, 213));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(108, 40, 96));
        jLabel8.setText("Total skill points:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        statsForLabel.setBackground(new java.awt.Color(109, 161, 213));
        statsForLabel.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        statsForLabel.setForeground(new java.awt.Color(252, 158, 4));
        statsForLabel.setText("Stats for: ");
        jPanel1.add(statsForLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel2.setBackground(new java.awt.Color(109, 161, 213));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 128)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(252, 158, 4));
        jLabel2.setText("VICTORY !!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        overlayLab.setBackground(new java.awt.Color(229, 214, 197));
        overlayLab.setOpaque(true);
        jPanel1.add(overlayLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 440, 420));

        overlayLab1.setBackground(new java.awt.Color(241, 234, 227));
        overlayLab1.setOpaque(true);
        jPanel1.add(overlayLab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 460, 440));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/victoryBG.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 800));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnToMMButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToMMButActionPerformed
        // TODO add your handling code here:
        BACKEND.DiceAndHandManager.clearHand();
        BACKEND.DiceAndHandManager.clearPosToReroll();
        BACKEND.DiceAndHandManager.clearDice();
        this.setVisible(false);
        MainMenuScreen mms = new MainMenuScreen();
        mms.setVisible(true);
    }//GEN-LAST:event_returnToMMButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VictoryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VictoryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VictoryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VictoryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VictoryScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel congratsMessage;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numMovesLab;
    private javax.swing.JLabel overlayLab;
    private javax.swing.JLabel overlayLab1;
    private javax.swing.JLabel pointsInMatchLab;
    private javax.swing.JButton returnToMMBut;
    private javax.swing.JLabel statsForLabel;
    private javax.swing.JLabel totalPointsLab;
    // End of variables declaration//GEN-END:variables
}
