/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.ImageIcon;

/**
 *
 * @author dhiys
 */
public class ViewDeckScreen extends javax.swing.JFrame {

    /**
     * Creates new form ViewDeck
     */
    public ViewDeckScreen() {
        initComponents();
        for (int i = 0; i < 3; i++) {
            viewCharsComboBox.addItem(BACKEND.ViewingManager.returnCharacter(i).getName());
           
        }
        for (int i = 0; i < 6; i++) {
            viewCardsComboBox.addItem(BACKEND.ViewingManager.returnCard(i).getName());
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        viewCardsComboBox = new javax.swing.JComboBox<>();
        viewCharsComboBox = new javax.swing.JComboBox<>();
        viewCharPanel = new javax.swing.JPanel();
        burstLab = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        elementLab = new javax.swing.JLabel();
        physLab = new javax.swing.JLabel();
        weaponLab = new javax.swing.JLabel();
        elemAtkLab = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        nameCharLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        loreTextArea = new javax.swing.JTextArea();
        viewSpecCardPanel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        descripLab = new javax.swing.JLabel();
        nameCardLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        returnToMMBut = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 19, 18));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(228, 217, 226));
        jLabel2.setText("Characters:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(228, 217, 226));
        jLabel3.setText("Special Cards:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 150, -1, -1));

        viewCardsComboBox.setBackground(new java.awt.Color(65, 49, 65));
        viewCardsComboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewCardsComboBox.setForeground(new java.awt.Color(255, 255, 255));
        viewCardsComboBox.setBorder(null);
        viewCardsComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        viewCardsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCardsComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(viewCardsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 210, 250, 60));

        viewCharsComboBox.setBackground(new java.awt.Color(65, 49, 65));
        viewCharsComboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewCharsComboBox.setForeground(new java.awt.Color(255, 255, 255));
        viewCharsComboBox.setBorder(null);
        viewCharsComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        viewCharsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCharsComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(viewCharsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 250, 60));

        viewCharPanel.setBackground(new java.awt.Color(26, 23, 25));
        viewCharPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        burstLab.setBackground(new java.awt.Color(228, 217, 226));
        burstLab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        burstLab.setForeground(new java.awt.Color(228, 217, 226));
        viewCharPanel.add(burstLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 220, 43));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(228, 217, 226));
        jLabel8.setText("Weapon: ");
        viewCharPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, 43));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(228, 217, 226));
        jLabel9.setText("Physical atk:");
        viewCharPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 43));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(228, 217, 226));
        jLabel10.setText("Elemental atk:");
        viewCharPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, 43));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(228, 217, 226));
        jLabel11.setText("Element:");
        viewCharPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, 43));

        elementLab.setBackground(new java.awt.Color(228, 217, 226));
        elementLab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        elementLab.setForeground(new java.awt.Color(228, 217, 226));
        viewCharPanel.add(elementLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 220, 43));

        physLab.setBackground(new java.awt.Color(228, 217, 226));
        physLab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        physLab.setForeground(new java.awt.Color(228, 217, 226));
        viewCharPanel.add(physLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 220, 43));

        weaponLab.setBackground(new java.awt.Color(228, 217, 226));
        weaponLab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        weaponLab.setForeground(new java.awt.Color(228, 217, 226));
        viewCharPanel.add(weaponLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 220, 43));

        elemAtkLab.setBackground(new java.awt.Color(228, 217, 226));
        elemAtkLab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        elemAtkLab.setForeground(new java.awt.Color(228, 217, 226));
        viewCharPanel.add(elemAtkLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 220, 43));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(228, 217, 226));
        jLabel16.setText("Burst atk:");
        viewCharPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 100, 43));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(228, 217, 226));
        jLabel17.setText("Lore:");
        viewCharPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 100, 43));

        nameCharLabel.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        nameCharLabel.setForeground(new java.awt.Color(228, 217, 226));
        nameCharLabel.setText("Name:");
        viewCharPanel.add(nameCharLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 43));

        loreTextArea.setBackground(new java.awt.Color(26, 23, 25));
        loreTextArea.setColumns(20);
        loreTextArea.setForeground(new java.awt.Color(228, 217, 226));
        loreTextArea.setRows(5);
        loreTextArea.setBorder(null);
        jScrollPane1.setViewportView(loreTextArea);

        viewCharPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 460, 70));

        jPanel1.add(viewCharPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 500, 500));

        viewSpecCardPanel.setBackground(new java.awt.Color(26, 23, 25));
        viewSpecCardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(228, 217, 226));
        jLabel24.setText("Description:");
        viewSpecCardPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, 43));

        descripLab.setBackground(new java.awt.Color(228, 217, 226));
        descripLab.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        descripLab.setForeground(new java.awt.Color(228, 217, 226));
        viewSpecCardPanel.add(descripLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 460, 100));

        nameCardLabel.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        nameCardLabel.setForeground(new java.awt.Color(228, 217, 226));
        nameCardLabel.setText("Name:");
        viewSpecCardPanel.add(nameCardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 43));

        jPanel1.add(viewSpecCardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 500, 500));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("RETURN TO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 100));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MAIN MENU");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 100));

        returnToMMBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/90x90button.png"))); // NOI18N
        returnToMMBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToMMButActionPerformed(evt);
            }
        });
        jPanel1.add(returnToMMBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 100));

        jLabel4.setBackground(new java.awt.Color(109, 161, 213));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(215, 148, 203));
        jLabel4.setText("View Deck");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewCardsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCardsComboBoxActionPerformed
        // TODO add your handling code here:
        String cardNameToView = (String) viewCardsComboBox.getSelectedItem();
        nameCardLabel.setText(BACKEND.ViewingManager.returnCard(cardNameToView).getName());
        descripLab.setText(BACKEND.ViewingManager.returnCard(cardNameToView).getDescription());
        
        
    }//GEN-LAST:event_viewCardsComboBoxActionPerformed

    private void viewCharsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCharsComboBoxActionPerformed
        // TODO add your handling code here:
        String charNameToView = (String) viewCharsComboBox.getSelectedItem();
        nameCharLabel.setText(BACKEND.ViewingManager.returnCharacter(charNameToView).getName());
        elementLab.setText(BACKEND.ViewingManager.returnCharacter(charNameToView).getElementType());
        weaponLab.setText(BACKEND.ViewingManager.returnCharacter(charNameToView).getWeaponType());
        physLab.setText(""+BACKEND.ViewingManager.returnCharacter(charNameToView).getPhysDmg());
        elemAtkLab.setText(""+BACKEND.ViewingManager.returnCharacter(charNameToView).getSkillDmg());
        burstLab.setText(""+BACKEND.ViewingManager.returnCharacter(charNameToView).getBurstDmg());
        loreTextArea.setText(BACKEND.ViewingManager.returnCharacter(charNameToView).getLore());
 
        
        
    }//GEN-LAST:event_viewCharsComboBoxActionPerformed

    private void returnToMMButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToMMButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainMenuScreen mms = new MainMenuScreen();
        mms.setVisible(true);

    }//GEN-LAST:event_returnToMMButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDeckScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDeckScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDeckScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDeckScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDeckScreen().setVisible(true);
            }
        });    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel burstLab;
    private javax.swing.JLabel descripLab;
    private javax.swing.JLabel elemAtkLab;
    private javax.swing.JLabel elementLab;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea loreTextArea;
    private javax.swing.JLabel nameCardLabel;
    private javax.swing.JLabel nameCharLabel;
    private javax.swing.JLabel physLab;
    private javax.swing.JButton returnToMMBut;
    private javax.swing.JComboBox<String> viewCardsComboBox;
    private javax.swing.JPanel viewCharPanel;
    private javax.swing.JComboBox<String> viewCharsComboBox;
    private javax.swing.JPanel viewSpecCardPanel;
    private javax.swing.JLabel weaponLab;
    // End of variables declaration//GEN-END:variables
}
