/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author dhiys
 */
public class ViewStats extends javax.swing.JFrame {

    /**
     * Creates new form ViewStats
     */
    public ViewStats() {
        initComponents();
        if (BACKEND.DeckManager.getHasADeck()) {
            charactersLabel.setText(BACKEND.StatsManager.getRecentDeckChars());
            cardsLabel.setText(BACKEND.StatsManager.getRecentDeckCards());
        } else {
            charactersLabel.setText("No previous characters.");
            cardsLabel.setText("No previous cards.");
        }
        
        statsForLabel.setText("Stats for: " + BACKEND.LoginManager.getUser());
        totalPointsLab.setText("" + BACKEND.StatsManager.countTotalPts(BACKEND.LoginManager.getUser()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        returnToMMBut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cardsLabel = new javax.swing.JTextArea();
        charactersLabel = new javax.swing.JLabel();
        statsForLabel1 = new javax.swing.JLabel();
        overlayLab2 = new javax.swing.JLabel();
        overlayLab3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalPointsLab = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        statsForLabel = new javax.swing.JLabel();
        overlayLab = new javax.swing.JLabel();
        overlayLab1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 19, 18));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnToMMBut.setBackground(new java.awt.Color(65, 49, 65));
        returnToMMBut.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        returnToMMBut.setForeground(new java.awt.Color(228, 217, 226));
        returnToMMBut.setText("Return To Main menu");
        returnToMMBut.setBorder(null);
        returnToMMBut.setPreferredSize(new java.awt.Dimension(286, 84));
        returnToMMBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToMMButActionPerformed(evt);
            }
        });
        jPanel1.add(returnToMMBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 690, 290, 80));

        cardsLabel.setBackground(new java.awt.Color(229, 214, 197));
        cardsLabel.setColumns(20);
        cardsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cardsLabel.setForeground(new java.awt.Color(108, 40, 96));
        cardsLabel.setRows(5);
        cardsLabel.setBorder(null);
        jScrollPane1.setViewportView(cardsLabel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 420, 130));

        charactersLabel.setBackground(new java.awt.Color(109, 161, 213));
        charactersLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        charactersLabel.setForeground(new java.awt.Color(108, 40, 96));
        jPanel1.add(charactersLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 420, 70));

        statsForLabel1.setBackground(new java.awt.Color(109, 161, 213));
        statsForLabel1.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        statsForLabel1.setForeground(new java.awt.Color(215, 148, 203));
        statsForLabel1.setText("Most recent deck:");
        jPanel1.add(statsForLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 360, 50));

        overlayLab2.setBackground(new java.awt.Color(229, 214, 197));
        overlayLab2.setOpaque(true);
        jPanel1.add(overlayLab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 440, 280));

        overlayLab3.setBackground(new java.awt.Color(241, 234, 227));
        overlayLab3.setOpaque(true);
        jPanel1.add(overlayLab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 460, 300));

        jLabel2.setBackground(new java.awt.Color(109, 161, 213));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 82)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(215, 148, 203));
        jLabel2.setText("View Stats");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        totalPointsLab.setBackground(new java.awt.Color(109, 161, 213));
        totalPointsLab.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        totalPointsLab.setForeground(new java.awt.Color(108, 40, 96));
        totalPointsLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(totalPointsLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 320, 50));

        messageLabel.setBackground(new java.awt.Color(109, 161, 213));
        messageLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(108, 40, 96));
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setText("Your progress so far");
        jPanel1.add(messageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-330, 220, 1170, -1));

        jLabel8.setBackground(new java.awt.Color(109, 161, 213));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(108, 40, 96));
        jLabel8.setText("Total skill points:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        statsForLabel.setBackground(new java.awt.Color(109, 161, 213));
        statsForLabel.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        statsForLabel.setForeground(new java.awt.Color(215, 148, 203));
        statsForLabel.setText("Stats for: ");
        jPanel1.add(statsForLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        overlayLab.setBackground(new java.awt.Color(229, 214, 197));
        overlayLab.setOpaque(true);
        jPanel1.add(overlayLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 440, 190));

        overlayLab1.setBackground(new java.awt.Color(241, 234, 227));
        overlayLab1.setOpaque(true);
        jPanel1.add(overlayLab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 460, 210));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/victoryBG.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1490, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnToMMButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToMMButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainMenuScreen mms = new MainMenuScreen();
        mms.setVisible(true);
    }//GEN-LAST:event_returnToMMButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewStats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JTextArea cardsLabel;
    private javax.swing.JLabel charactersLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel overlayLab;
    private javax.swing.JLabel overlayLab1;
    private javax.swing.JLabel overlayLab2;
    private javax.swing.JLabel overlayLab3;
    private javax.swing.JButton returnToMMBut;
    private javax.swing.JLabel statsForLabel;
    private javax.swing.JLabel statsForLabel1;
    private javax.swing.JLabel totalPointsLab;
    // End of variables declaration//GEN-END:variables
}
